/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomSheet: typeof import('./src/components/BottomSheet.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    ExpenseCreateForm: typeof import('./src/components/ExpenseCreateForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ItineraryCreateForm: typeof import('./src/components/ItineraryCreateForm.vue')['default']
    ItineraryItemActions: typeof import('./src/components/ItineraryItemActions.vue')['default']
    NoteForm: typeof import('./src/components/NoteForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastContainer: typeof import('./src/components/common/ToastContainer.vue')['default']
  }
}
